[project]
authors = ["Aaditya Pal <107549181+Aaditya18SP@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "Mojo-Yolo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.4.0,<25"
transformers = ">=4.41.2,<5"
pillow = ">=10.4.0,<11"
pytorch = ">=2.4.0,<3"
opencv = ">=4.10.0,<5"
psutil = ">=6.0.0,<7"
